### ISSUE TITLE
Status and Roadmap for e-2-e?

### ISSUE THREAD

**Issue by zeigerpuppy** [nextcloud/end_to_end_encryption#285]
End to End Encryption appears to be in an alpha state at the moment.

It appears that updates since 2020 have been largely version bumps to allow installation on newer NC versions (up to v22) but have not resolved issues with the functionality/stability.

It would be good to get an update from devs on the plans for this app, even if the status is "abandoned".

Moving forward, if we can identify the main needs to make it functional (i.e. alpha -> beta needs), then a fork may be warranted to get this working.

**Comment by karlemilnikka** [comment]
Yes, a status update would be very welcome. In the meanwhile, I have to assume that the project is abandoned since we’re getting close to Nextcloud 24 and the app is still incompatible with Nextcloud 23. [The roadmap](https://nextcloud.com/endtoend/) is also not updated. :-(

**Comment by develop-Greenant** [comment]
Just starting a little list, feel free to amend and we can gather together as we go...

## End-2-End Encryption Features:

Tested on Server v22.2.5 (Linux)

### Working (show tested version):

- [x] create e2e folder
- [x] enter e2e mnemonic
- [x] sync with Linux client v3.4.1
- [x] sync with OS X client v3.2.1

### Not Working

- [ ] share encrypted folder - not allowed from web interface or desktop clients

**Comment by BirdInFire** [comment]
> End to End Encryption appears to be in an alpha state at the moment.
> 
> It appears that updates since 2020 have been largely version bumps to allow installation on newer NC versions (up to v22) but have not resolved issues with the functionality/stability.
> 
> It would be good to get an update from devs on the plans for this app, even if the status is "abandoned".
> 
> Moving forward, if we can identify the main needs to make it functional (i.e. alpha -> beta needs), then a fork may be warranted to get this working.

Since they do not even do an official response, (from member to dev) it mean it's already abandoned.

**Comment by betooo0997** [comment]
I don't understand why this is abandoned. Isn't E2EE a [key feature](https://nextcloud.com/endtoend/)?

**Comment by BirdInFire** [comment]
> I don't understand why this is abandoned. Isn't E2EE a [key feature](https://nextcloud.com/endtoend/)?

in my case i have started to moveout to seafile, i do not use all their shiny (who really heavily on "password app") dav function, and seafile their built in client side encryption do work.

**Comment by BirdInFire** [comment]
So the lack of answer mean we can safely say it's totally abandoned from nextcloud and stop recommend them altogether ??

**Comment by develop-Greenant** [comment]
@BirdInFire I think it is safe to assume, as you say, that e2e has been abandoned.  

However, the point of this issue is to review a path forward, it is open-source after all!

The basic e2e implementation is, thankfully, working.  I think the path forward will be to fork the e2e module and then look at implementing the required features to make it more useful.  In my use-case, I'd be happy even if we just managed to get sharing of e2e folders working.

Very keen to hear from any crypto-nerds as to suggestions on next steps.  If there's a clear path, I think we could find some funding to help push this forward too.

**Comment by develop-Greenant** [comment]
p.s. nice to see that Seafile now supports document editing with collabora.  Although I am curious how that can work with encryption, I don't think that's possible while the server is zero-knowledge.

**Comment by BirdInFire** [comment]
> p.s. nice to see that Seafile now supports document editing with collabora. Although I am curious how that can work with encryption, I don't think that's possible while the server is zero-knowledge.
> 
> [edit for details]
> 
> Looks like server caches password for 1hr:
> 
> https://help.seafile.com/security_and_encryption/use_encrypted_libraries/
> 
> > If you use web app, you have to input the password to the server. The server will cache the password in encrypted format for 1 hour. It won't store the password on disk.
> 
> That certainly could lead to compromise of encrypted files if the server was compromised.

yeah it's why i do not use the server, after all i have ditched nextcloud because of that.
i only want a sync service, and use native app on my device to do the job.

**Comment by zeigerpuppy** [comment]
OK, best to get back on topic.  Seafile encryption is interesting, but doesn't seem to solve the main missing feature described above, which is sharing of encrypted folders/libraries.

**Comment by purdieb** [comment]
> @BirdInFire I think it is safe to assume, as you say, that e2e has been abandoned.
> 
> However, the point of this issue is to review a path forward, it is open-source after all!
> 
> The basic e2e implementation is, thankfully, working. I think the path forward will be to fork the e2e module and then look at implementing the required features to make it more useful. In my use-case, I'd be happy even if we just managed to get sharing of e2e folders working.
> 
> Very keen to hear from any crypto-nerds as to suggestions on next steps. If there's a clear path, I think we could find some funding to help push this forward too.

I believe much of the functionality required for end to end encryption is present within this add on. The majority of the end to end encryption logic that would require changing is in the nextcloud clients.

Adding shared folders to nextcloud's end to end encryption would require modifying the clients code (and the metadata format) so that it encrypts the metadata key using the public keys of all recipient users. The metadata format currently used by nextcloud cannot support shared folders. The client would also need to be modified to store the list of users and their public keys locally. This would then need to be exposed in the UI (although you can probably do this just using the normal folder sharing UI for the nextcloud client, just need to remove the check that prevents it from showing for encrypted folders).

**Comment by zeigerpuppy** [comment]
Thanks @purdieb that's some good pointers, I guess filing an issue in the client repo would also be a good idea.

**Comment by BirdInFire** [comment]
> Thanks @purdieb that's some good pointers, I guess filing an issue in the client repo would also be a good idea.

since they do not even respond here to the core E2E (even a "we are aware of the issue yada yada yada") do not push your hope to much :(

**Comment by zeigerpuppy** [comment]
> > Thanks @purdieb that's some good pointers, I guess filing an issue in the client repo would also be a good idea.
> 
> since they do not even respond here to the core E2E (even a "we are aware of the issue yada yada yada") do not push your hope to much :(

As this is open source software we do not need "them" to respond, just to find a solution!

**Comment by BirdInFire** [comment]
> > > Thanks @purdieb that's some good pointers, I guess filing an issue in the client repo would also be a good idea.
> > 
> > 
> > since they do not even respond here to the core E2E (even a "we are aware of the issue yada yada yada") do not push your hope to much :(
> 
> As this is open source software we do not need "them" to respond, just to find a solution!

True but i will not help on this one, don't want to really help the people who doesn't have the respect to tell the community if it's on hold or abandoned, nor even respond on this for so much time.

**Comment by AndyScherzinger** [comment]
Sorry for the wait while this has been raised elsewhere and also answered elsewhere, see https://github.com/nextcloud/end_to_end_encryption/issues/273#issuecomment-1091648311 -

> I'm afraid we are 100% transparent: there has never been a decision to NOT work on the E2E app, or to drop it. So there is nothing to announce. It's been on todo lists to update the app forever. But every week we have to pick the tasks to work on for the week, other things were more urgent, be it customer problems and features they pay for or the thousands of other issues people ask about in the community.
>
> I maintain the website and I'd also prefer the site to be in line with what is the state of things is - but I know as much as you do. So my heuristic is usually "if an app is not available for a release that gets updated, it's time to remove the feature from the website". This app is available for Nextcloud 22 from what I can see in the app store, so I haven't thought about removing it yet.
>
> As Joas said, somebody was assigned the task to work on it, but if they get sick or if other higher priority things come up - it might not happen. In the end, it's like in any other open source project: either somebody volunteers or somebody gets paid to do something. Everyone here in the chat is welcome to step up in either of those ways!

It has been made available for 23 by @CarlSchwan and is currently being worked on to be available for 24 as well. New features haven't yet been implemented since there also haven't been any customer requests for that and like @jospoortvliet stated in the cited statement above we continuously need to decide on priorities. So yes we would love to push this forward but currently have a different focus, the project definitely isn't abondoned but alive while more in a maintenance way than pushing forward the feature set.

**Comment by DanScharon** [comment]
@AndyScherzinger customer requests incoming 😄

**Comment by karlemilnikka** [comment]
@AndyScherzinger Thank you very much for the clarification. You might want to update the [official web page]( https://nextcloud.com/endtoend/) and roadmap. In case customers are reading it, they might think the information describes the project’s current status rather than where it was supposed to be. 

”Nextcloud features an enterprise-grade, seamlessly integrated solution for end-to-end encryption. It enables users to pick one or more folders on their desktop or mobile client for end-to-end encryption. **Folders can be shared with other users** and synced between devices but are not readable by the server.”

**Comment by AndyScherzinger** [comment]
so cc @jospoortvliet for https://github.com/nextcloud/end_to_end_encryption/issues/285#issuecomment-1123345416 thanks for pointing that out @karlemilnikka 🙏 

@DanScharon looking forward to it 👍

**Comment by AndyScherzinger** [comment]
Also just as a side-note or reminder because like mentioned by some of you before this is OSS and this repo is here so anybody is free and very welcome to contribute. So if anybody is up for it, please go for it, we support you implementing it as good as we can with being there for the solution discussions/design as well as reviews and answering potential question one might come up with.

**Comment by jospoortvliet** [comment]
> @AndyScherzinger Thank you very much for the clarification. You might want to update the [official web page](https://nextcloud.com/endtoend/) and roadmap. In case customers are reading it, they might think the information describes the project’s current status rather than where it was supposed to be.
> 
> ”Nextcloud features an enterprise-grade, seamlessly integrated solution for end-to-end encryption. It enables users to pick one or more folders on their desktop or mobile client for end-to-end encryption. **Folders can be shared with other users** and synced between devices but are not readable by the server.”

The top of the page states:
"In particular, as of May 2022, offline recovery, sharing and HSM features are on the roadmap."  (date was Jan 2021, I updated it to May 2022)

Will suffice, I hope.

**Comment by BirdInFire** [comment]
and one month later dead again, and the full lie on the website "Note: our end-to-end encryption solution is under constant development.", the only guy who pass here to commit is the bot....

**Comment by karlemilnikka** [comment]
> and one month later dead again, and the full lie on the website "Note: our end-to-end encryption solution is under constant development.", the only guy who pass here to commit is the bot....

Yes. Since the project is just maintained to keep the existing functionality, and no work on the roadmap features will be done for the foreseeable future, it would be better to just be up front with it on the website. Remove everything regarding offline recovery, sharing, HSM and "enterprise grade/production ready", and promote the existing functionality instead. Even though the existing functionality is far from what’s currently promoted, it’s better than competing mainstream solutions like Onedrive or Google Drive that don’t offer E2EE at all.

**Comment by AndyScherzinger** [comment]
> and one month later dead again, and the full lie on the website "Note: our end-to-end encryption solution is under constant development.", the only guy who pass here to commit is the bot....

E2EE is more than just the server-side app, looking at recent Android PRs, i.e.
* https://github.com/nextcloud/android/pull/10390
* https://github.com/nextcloud/android/pull/10388
* https://github.com/nextcloud/android/pull/10323
* https://github.com/nextcloud/android/pull/10322

> on the website. Remove everything regarding offline recovery, sharing, HSM and "enterprise grade/production ready", and promote the existing functionality instead.

Just to be clear, this is the tracker for the server-side app for e2ee (the project) and has no relation to the website which is purely operated by Nextcloud (as a company).

**Comment by karlemilnikka** [comment]
> 

Thanks for the clarification.

**Comment by melMass** [comment]
Trying to catch up with this thread after seing the half star review on the store... 
@AndyScherzinger is there still a dedicated person for this? / A kanban to follow progress?

Thanks

**Comment by AndyScherzinger** [comment]
> is there still a dedicated person for this? / A kanban to follow progress?

There is a dedicated person for this in cases where we decide to add enhancements to e2ee, yes.
There is no kanban to follow progress and it is also not planned to have a dedicated one.
We currently work on getting a "server/files"-related kanban board up again - used the quotation marks since that board would cover anything files or server related.

**Comment by karlemilnikka** [comment]
Thanks for the update, @AndyScherzinger. Do you think the development of any of the features listed as coming in 2021 or 2022 (on the official E2EE roadmap) will be continued this year?

**Comment by karlemilnikka** [comment]
@AndyScherzinger, I appreciate your honest reply.

**Comment by karlemilnikka** [comment]
I really appreciated you sharing your gut-feeling earlier this year, @AndyScherzinger. Can you share it again regarding 2023? Do you think there will be any progress made during the year or is the development of the missing marketed features put on hold for the foreseeable future?

**Comment by AndyScherzinger** [comment]
I do not have an officially communicate-able roadmap but what I can disclose is that we currently picked up work on e2ee features to likely see the light of day with Nextcloud 26. So for the ones on the published roadmap there is currently no updates (also no customer demand). So again for the existing items on the map any contributions - as always - are welcome and developers will help and support in any way needed.

**Comment by karlemilnikka** [comment]
Thank you very much for your reply, @AndyScherzinger. Even though it wasn’t the answer I was hoping for, I appreciate it since we then can put all focus on Cryptomator Hub instead. 

Please consider updating the marketing page as well to keep it in line with reality and state of the project. In my opinion, it would benefit Nextcloud to be honest with the app’s limitations and only list features that actually work instead of calling it “enterprise grade” and list features that won’t see the light of day for any foreseeable future.

**Comment by karlemilnikka** [comment]
> > (also no customer demand)
> 
> This surprises me considering that e2ee will most likely play an important role in the future of GDPR and data protection in general.

Yes, that also caught me off guard. I thought it was one of the most demanded features, but I guess I was wrong. Maybe Nextcloud customers are different from Apple’s customers (iCloud Drive will get E2EE support next year), Dropbox’ customers (Dropbox just acquired Boxcryptor) and existing enterprise grade services with E2EE support like Tresorit and Sync.com.

**Comment by karlemilnikka** [comment]
> > “enterprise grade”.
> 
> I agree with what you said, but "entreprise grade" is an empty marketing thing since Entreprise all have differents security model.
> 
> Because i know a dozen of entreprise where E2EE is mandatory since they do not "physically" control the hardware or want to protect their customer data if a server breach occur.

I wasn’t calling Nextcloud E2EE enterprise grade. I was saying the opposite, that it shouldn’t be called enterprise grade.

**Comment by karlemilnikka** [comment]
Just like @jcassette, I would also love to know how much money that’s needed. Preferably, broken down on how much money that’s needed for ongoing maintenance (rolling need) and how much that’s initially needed to make the app stable with current feature set. If possible, it would also be great to know how much money that’s needed to actually build the features that were marketed as [existing back in 2020](https://web.archive.org/web/20201204235908/https://nextcloud.com/endtoend/) and currently are labeled as "roadmap features" .

**Comment by Freeedim** [comment]
@AndyScherzinger I think you are wrong when saying there is no demand for a real production-ready E2EE feature with folder sharing. I have been reading and contributing to countless threads on this for the past 3+ years, in the forums, in GitHub and in real life among information management practitioners.

The communication and marketing content have been misleading for 3+ years now, which is very bad for Nextcloud's reputation and credibility.

About the main topic of finding a solution, which I think is a great idea, I have been wondering if it is possible to recycle the code of projects like [gocryptfs](https://github.com/rfjakob/gocryptfs) or [rclone](https://github.com/rclone/rclone). Then, not being a developer myself, I don't know how difficult it is to:
- implement a folder sharing based on asymmetric encryption of each encryption key;
- integrate the functions into the shells (righ-click menus) in KDE Plasma, Gnome, Windows, MacOS...

I am myself using dirty scripts to automate/integrate things as much as I can, based on gocryptfs (looking to rclone for the future) for the encryption part and KeePassXC for the key sharing part. I just wish someone was able to put all those rambling elements altogether in a clean and installable way (after having just wished Nextcloud developers would do it as advertised).

Are there any thoughts on this?

**Comment by karlemilnikka** [comment]
@Freeedim Support for sharing E2EE encrypted folders was introduced with [Nextcloud Hub 4 (Nextcloud 26)](https://nextcloud.com/encryption/). The E2EE implementation was however still far from production ready. It broke versioning (even for non-encrypted files), and it accidentally deleted all my files when I enabled it. 

I just upgraded to Nextcloud Hub 5 (Nextcloud 27) and the latest version of the E2EE app. So far, I haven’t lost any data. Versioning is still broken though. Regardless of that, I’m so happy to see progress on the E2EE front!

**Comment by Freeedim** [comment]
@karlemilnikka Thank you so much for reporting this. I have actually landed here while searching where Nextcloud is standing right now regarding E2EE, as yet another client asks me whether it would be a good solution to them (which requires sharing E2EE folders). So I am happy to know there is progress.

Let me give it a try in a test instance...

**Comment by dbrgn** [comment]
Thanks for the honest feedback in the thread so far.

> So for the ones on the published roadmap there is currently no updates (also no customer demand).

It's interesting that there appears to be no customer demand, while the [introductory blogpost](https://nextcloud.com/blog/nextcloud-introducing-native-integrated-end-to-end-encryption/) – published 6 years ago – claimed:

> We are [excited to announce](https://nextcloud.com/press/pr20170927/) what is **probably the all-time most requested feature** in the 7-year history of our open source file sync and share work: End-to-end Encryption, also called Client Side Encryption.

I wondered whether or not to comment here, usually I don't think it's helpful, but since the reason for stalled progresss is "lack of demand", I decided to comment anyways. I, too, am currently evaluating NextCloud as a data snychronization solution.  I came to it after [checking the website, and reading that](https://nextcloud.com/encryption/) it has "an enterprise-grade, seamlessly integrated solution for end-to-end encryption". The website also claims "folders can be shared with other users and synced between devices but are never readable by the server". If there is any doubt on whether the solution is already stable, that was dispersed by the sentence "our solution is enterprise ready". And I'm certain that enterprises don't want to lose any data!

After reading this thread, it seems that most of these claims are not true as of 2023, and if stable E2EE is a requirement, NextCloud currently isn't the solution. Apparently the feature was never completed, many of the [nicely promoted properties of the end-to-end encryption on the website](https://nextcloud.com/features/#end-to-end) have a "not yet implemented" note next to them, and there appears to be no roadmap by when these features will be ready.

The number one reason for using NextCloud – as opposed to a public cloud – must surely be the control over data. E2EE is the pinnacle of data protection. It would be great if this aspect could get more priority.

(Also, I realize that this issue is mainly about nextcloud project, and not the nextcloud.com website, but if a website [uses the term](https://nextcloud.com/encryption/) "military-grade encryption", then to me as a techie this is an indicator that it might just be snakeoil. What I'd like to see instead, is "rock-solid, open and audited encryption protocols".)

**Comment by Freeedim** [comment]
Indeed... 
After my hopeful comment above, I eventually test v27.1, and was again very disappointed. There was some progress, E2EE is easier, more user friendly and mess buggy. But E2EE folder sharing still doesn't work at all. It was already advertised as "production-ready" in 2019, then marked on the roadmap for 2020.

**Comment by jospoortvliet** [comment]
Hi all,

My regular check-in on this discussion ;-)

Glad to see you notice we make some progress. And yes I know, it's not perfect yet, but we'll keep moving piece by piece, more over time as our customer and thus developer base grows. We have some enterprise customers using E2EE, so we can put some engineering effort in fixing issues they encounter.

With regards to fluffy words like military-grade encryption - I hear yah, I am not a fan of it either. But it's kind of a race, you know. When another company calls their boring SHA256 hashing 'military grade', I also smirk, but then a not-technical manager might compare, and see we do NOT have military grade encryption! So surely, the other company (that might not have published a CVE in 3 years) must be BETTER.

So hum, we have to play the game, even if we don't like it.

**Comment by bcutter** [comment]
While searching for errors I get with E2EE on iOS (https://github.com/nextcloud/ios/issues/2809) I came across https://ethz.ch/content/dam/ethz/special-interest/infk/inst-infsec/appliedcrypto/education/theses/nextcloud.pdf listed at the top of Google search results, where 2 out of 3 issues seem to have been addressed. But there are serious aspects in the 6th chapter (conclusion).

I'd really like to read a reaction to that paper in general and the points in chapter 6 in particular, maybe that happened already somewhere else. But when it comes to the "status and roadmap" of E2EE (this issue), this paper for sure is a notable input.

**Comment by zeigerpuppy** [comment]
An interesting paper, thanks @bcutter 
They make some very relevant points regarding the importance of implementation plans for encryption features and advise against releasing untested/beta features.

It would be great to see a functional E2EE feature in Nextcloud, but in its current state it would be far better to advise users to use a layered approach (encrypt using a local program and then share keys out-of-band).

**Comment by DanScharon** [comment]
> Indeed... After my hopeful comment above, I eventually tested v27.1, and was again very disappointed. There was some progress, E2EE is easier, more user friendly and less buggy. But E2EE folder sharing still doesn't work at all. It was already advertised as "production-ready" in 2019, then marked on the roadmap for 2020.

is E2EE folder sharing supported now with v28 or v29?

**Comment by AndyScherzinger** [comment]
I do think v29, educated guess...

@tobiasKaminsky can you confirm which version?

**Comment by alexanderdd** [comment]
> > Indeed... After my hopeful comment above, I eventually tested v27.1, and was again very disappointed. There was some progress, E2EE is easier, more user friendly and less buggy. But E2EE folder sharing still doesn't work at all. It was already advertised as "production-ready" in 2019, then marked on the roadmap for 2020.
> 
> is E2EE folder sharing supported now with v28 or v29?

@DanScharon it definitely works in the client with NC 31. Did not test other versions.
